server:
  port: 9039
  tomcat:
    #如下配置是根据4核8G内存单进程服务器配置
    #等待队列长度,默认100（队列也做缓冲池用，但也不能无限长， 不但消耗内存，而且出队入队也消耗CPU）
    accept-count: 1000  #最大的等待数
    #tomcat默认最大线程数为200   具体根据服务器配置调整
    max-threads: 400
    #最大连接数
    max-connections: 10000
    # 最小工作空闲线程数，默认10。（适当增大一些，以便应对突然增长的访问量）
    min-spare-threads: 100
spring:
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 8
        max-wait: 3000ms
    timeout: 10000ms