package com.example.ddd.infrastructure.utils.enums;

public enum EntityType {
    TENANT, CUSTOMER, USER, DASHBOARD, ASSET, DEVICE, ALARM, RULE_CHAIN, RULE_NODE, ENTITY_VIEW, WIDGETS_BUNDLE, WIDGET_TYPE,UPGRADE_DEVICE,BROKER,TOPIC,
    DEVICE_SUPPLIER_TYPE_TOPIC,DEVICE_SUPPLIER_TYPE
}
