server:
  port: 9091
spring:
  application:
    #在sentinel控制台的名称
    name: sentinel-test
  sentinel:
    transport:
      port: 9719
      #设置sentinel控制台地址
      dashboard: localhost:8080
      heartbeat-interval-ms: 5
    eager: true
    datasoruce:
      #熔断配置
      ds1:
        apollo:
          namespace-name: application
          flow-rules-key: degrade-rules
          data-type: json
          rule-type: DEGRADE